name: linker2
description: A flutter plugin to link with other app or system function.
version: 0.0.2
homepage: https://github.com/jimczj/linker

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.github.jzoom.linker
        pluginClass: LinkerPlugin
      ios:
        pluginClass: LinkerPlugin